import { NextRequest, NextResponse } from "next/server";
import { prisma, isDatabaseConfigured } from "@/lib/prisma";
import { tryFulfillForNewLead } from "@/lib/fulfillment";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * GoHighLevel → Advertisely lead intake.
 *
 * Leads are now generated by a GHL-hosted form (Meta ads drive traffic to it),
 * so every lead is born in Enhanced Wealth's GHL. A GHL workflow ("Form
 * submitted" → Webhook action) POSTs the new contact here. We mirror it into
 * the Advertisely marketplace as the source of truth for availability.
 *
 * Because the lead comes FROM GHL, the GHL contact id arrives in the payload —
 * we store it so that when the lead is later purchased we can tag that exact
 * contact `advertisely-sold` and pull it out of Enhanced Wealth's dialing view.
 *
 * Auth: a shared secret sent by GHL either as the `x-advertisely-secret`
 * header or a `?secret=` query param, compared against GHL_WEBHOOK_SECRET.
 */

// Default marketplace package new GHL leads belong to. Fresh vs Aged is derived
// from receivedAt at query time, not stored here.
const DEFAULT_PACKAGE_ID = "blue-collar-iul";

/** Pull a value from a loose object trying several possible key spellings. */
function pick(obj: Record<string, any>, keys: string[]): string | undefined {
  for (const k of keys) {
    // exact
    if (obj[k] != null && obj[k] !== "") return String(obj[k]);
    // case-insensitive
    const hit = Object.keys(obj).find((o) => o.toLowerCase() === k.toLowerCase());
    if (hit && obj[hit] != null && obj[hit] !== "") return String(obj[hit]);
  }
  return undefined;
}

export async function POST(req: NextRequest) {
  // ── Auth ──────────────────────────────────────────────────────────
  const secret = process.env.GHL_WEBHOOK_SECRET;
  if (!secret) {
    return NextResponse.json(
      { error: "GHL_WEBHOOK_SECRET not configured" },
      { status: 503 },
    );
  }
  const provided =
    req.headers.get("x-advertisely-secret") ??
    new URL(req.url).searchParams.get("secret");
  if (provided !== secret) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!isDatabaseConfigured || !prisma) {
    return NextResponse.json(
      { error: "Database not configured" },
      { status: 503 },
    );
  }

  // ── Parse ─────────────────────────────────────────────────────────
  let body: Record<string, any>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  // GHL sometimes nests contact data under `contact` / `customData`; flatten so
  // the tolerant field-picker sees everything at the top level.
  const flat: Record<string, any> = {
    ...body,
    ...(body.contact ?? {}),
    ...(body.customData ?? {}),
    ...(body.custom_data ?? {}),
  };

  // ── Map standard fields (tolerant to GHL's key spellings) ─────────
  const ghlContactId = pick(flat, [
    "contact_id",
    "contactId",
    "id",
    "contactID",
  ]);

  const fullName =
    pick(flat, ["full_name", "fullName", "name"]) ??
    [pick(flat, ["first_name", "firstName"]), pick(flat, ["last_name", "lastName"])]
      .filter(Boolean)
      .join(" ")
      .trim();

  const phone = pick(flat, ["phone", "phone_number", "phoneNumber"]);
  const email = pick(flat, ["email", "email_address"]) ?? "";
  const state = pick(flat, ["state", "us_state", "State"]) ?? "";
  const ageRaw = pick(flat, ["age"]);
  const age = ageRaw ? parseInt(ageRaw.replace(/[^0-9]/g, ""), 10) || null : null;
  const incomeRaw = pick(flat, ["income", "household_income", "annual_income"]);
  const income = incomeRaw
    ? parseInt(incomeRaw.replace(/[^0-9]/g, ""), 10) || null
    : null;
  const occupation = pick(flat, ["occupation", "job", "profession"]) ?? null;
  const intentReason =
    pick(flat, [
      "intent",
      "intent_reason",
      "iul_interest",
      "reason",
      "why_interested",
    ]) ?? null;

  // Attribution
  const utmSource = pick(flat, ["utm_source", "utmSource"]) ?? null;
  const utmMedium = pick(flat, ["utm_medium", "utmMedium"]) ?? null;
  const utmCampaign = pick(flat, ["utm_campaign", "utmCampaign"]) ?? null;
  const fbclid = pick(flat, ["fbclid", "fbc"]) ?? null;

  // Consent
  const trustedFormUrl =
    pick(flat, ["trustedform", "trusted_form", "xxTrustedFormCertUrl", "cert_url"]) ??
    null;
  const consentIp = pick(flat, ["ip", "ip_address", "consent_ip"]) ?? null;

  const packageId = pick(flat, ["package", "packageId", "package_id"]) ?? DEFAULT_PACKAGE_ID;
  const sourceLabel =
    pick(flat, ["source", "form_name", "formName"]) ?? "GHL Form";

  // Minimum viable lead: we need a phone (the dial identifier) and a name.
  if (!phone || !fullName) {
    return NextResponse.json(
      { error: "Missing required fields (name and phone)" },
      { status: 400 },
    );
  }

  // ── Idempotent upsert (keyed on GHL contact id when present) ──────
  try {
    if (ghlContactId) {
      const existing = await prisma.lead.findUnique({
        where: { ghlContactId },
      });
      if (existing) {
        // Update-in-place: GHL fired again for a contact we already have.
        await prisma.lead.update({
          where: { ghlContactId },
          data: {
            name: fullName,
            phone,
            email,
            state,
            age: age ?? undefined,
            income: income ?? undefined,
            occupation: occupation ?? undefined,
            intentReason: intentReason ?? undefined,
            trustedFormUrl: trustedFormUrl ?? undefined,
            rawFormData: flat,
          },
        });
        return NextResponse.json({ ok: true, leadId: existing.id, updated: true });
      }
    }

    const created = await prisma.lead.create({
      data: {
        ghlContactId: ghlContactId ?? undefined,
        name: fullName,
        phone,
        email,
        state,
        age,
        income,
        occupation,
        intentReason,
        packageId,
        source: `GHL Form - ${sourceLabel}`,
        utmSource,
        utmMedium,
        utmCampaign,
        fbclid,
        consentMethod: "TCPA_WEB_FORM",
        consentTime: new Date(),
        consentIp,
        trustedFormUrl,
        rawFormData: flat,
        activity: {
          create: {
            type: "LEAD_RECEIVED",
            body: `Lead received from GHL form "${sourceLabel}".`,
          },
        },
      },
    });

    // If a matching order is already waiting, assign immediately.
    await tryFulfillForNewLead(created.id).catch((e) =>
      console.warn("Fulfillment after GHL intake failed:", e),
    );

    return NextResponse.json({ ok: true, leadId: created.id, created: true });
  } catch (err) {
    console.error("GHL intake failed:", err);
    return NextResponse.json(
      { error: "Failed to store lead" },
      { status: 500 },
    );
  }
}

// GHL/health-check pings sometimes GET the endpoint — respond cleanly.
export async function GET() {
  return NextResponse.json({ ok: true, endpoint: "ghl-intake" });
}
